# Load Oh My Zsh
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"
plugins=(git zsh-autosuggestions zsh-syntax-highlighting)
source $ZSH/oh-my-zsh.sh

# Load aliases
source $HOME/.config/zsh/aliases.zsh

# Starship prompt
eval "$(starship init zsh)"

# FZF keybindings
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# zoxide
eval "$(zoxide init zsh)"

# General
export EDITOR=nvim
export VISUAL=nvim
